### ISSUE TITLE
USB adapter

### ISSUE THREAD

**Issue by nprobert** [jfpastrana/802.11p#1]
Not many newer laptops have the PCIe slot anymore, but there is a USB adapter which makes it easier.

https://www.amazon.com/gp/product/B07FJXNLLT/ref=ox_sc_act_title_1?smid=A3JG90J1GP6HGX&psc=1

**Comment by jfpastrana** [comment]
Hi @nprobert 

Thanks for the contribution. However, it does not work. Few years ago, I had tested one adapter similar to this one. Moreover, it is clear in the description of the article::

- "Note: ONLY work for WWAN(Wireless Wide Area Network) card, CANNOT work for MSATA SSD or WLAN Card. "

- "... cards to this adapter then plug to USB port, doesn’t support PCI-E bus type minicard such as Wifi module"

- "1.Doesn’t support PCI-E bus type minicard such as Wifi module, only supports USB bus interface of Mini-Cards such as 2G GSM, GPRS, 3G, CDMA, WLAN, WWLAN, HSPA MODEM, GPS, 4G WiMAX, LTE, and Mini-Card to desktop PC "

Regards
